/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: ["class", "[data-theme='dark']"],
  theme: {
    borderRadius: {
      none:    "0",
      DEFAULT: "0",
      sm:      "0",
      md:      "0",
      lg:      "0",
      xl:      "0",
      "2xl":   "0",
      full:    "9999px", // ONLY for vinyl disc — no other use
    },
    fontFamily: {
      serif:   ["Instrument Serif", "Georgia", "serif"],
      display: ["Funnel Display", "Helvetica Neue", "sans-serif"],
      sans:    ["Funnel Sans", "Helvetica Neue", "sans-serif"],
    },
    extend: {
      colors: {
        paper:   "#F6F6F0",
        cream:   "#EFEEEA",
        sleeve:  "#CEC6B9",
        forest:  "#204F41",
        amber:   "#CD9121",
        plum:    "#322B55",
        wax:     "#9A181A",
        caramel: "#B28B58",
        ink:     "#141313",
        "slabs-bg":            "#F6F6F0",
        "slabs-surface":       "#EFEEEA",
        "slabs-surface-muted": "#CEC6B9",
        "slabs-text":          "#141313",
        "slabs-text-muted":    "#4E4843",
        "slabs-text-faint":    "#6B6257",
        "slabs-primary":       "#204F41",
        "slabs-price":         "#204F41",
        "slabs-error":         "#9A181A",
        "slabs-border":        "rgba(20,19,19,0.12)",
        "slabs-divider":       "rgba(20,19,19,0.08)",
        "dark-bg":             "#141313",
        "dark-surface":        "#242120",
        "dark-surface-muted":  "#323030",
        "dark-primary":        "#3D8468",
        "dark-accent":         "#E8A830",
        "dark-text":           "#EFEEEA",
        "dark-text-muted":     "#A09589",
        "dark-text-faint":     "#6B6257",
        "dark-price":          "#E8A830",
        "dark-error":          "#C4332A",
        "dark-border":         "rgba(239,238,234,0.10)",
        "dark-divider":        "rgba(239,238,234,0.07)",
      },
      fontSize: {
        "display-xl": ["clamp(3rem,0.5rem+7vw,8rem)",         { lineHeight: "1.03", letterSpacing: "-0.025em" }],
        "display-lg": ["clamp(2.5rem,1rem+4vw,5rem)",         { lineHeight: "1.06", letterSpacing: "-0.02em"  }],
        "display-md": ["clamp(2rem,1.2rem+2.5vw,3.5rem)",     { lineHeight: "1.10", letterSpacing: "-0.015em" }],
        "display-sm": ["clamp(1.5rem,1.2rem+1.25vw,2.25rem)", { lineHeight: "1.18", letterSpacing: "-0.01em"  }],
        "ui-h4":    ["1.25rem",   { lineHeight: "1.25", letterSpacing: "-0.005em" }],
        "ui-h5":    ["1rem",      { lineHeight: "1.30" }],
        "ui-nav":   ["0.875rem",  { lineHeight: "1.20", letterSpacing: "0.01em"  }],
        "ui-label": ["0.75rem",   { lineHeight: "1.0",  letterSpacing: "0.08em"  }],
        "ui-meta":  ["0.6875rem", { lineHeight: "2.0",  letterSpacing: "0.08em"  }],
        "ui-over":  ["0.625rem",  { lineHeight: "1.0",  letterSpacing: "0.12em"  }],
        "body-lg":  ["1.125rem",  { lineHeight: "1.70" }],
        "body-md":  ["1rem",      { lineHeight: "1.65" }],
        "body-sm":  ["0.875rem",  { lineHeight: "1.60" }],
        "body-xs":  ["0.75rem",   { lineHeight: "1.50", letterSpacing: "0.01em" }],
      },
      transitionTimingFunction: {
        analog: "cubic-bezier(0.25, 0.1, 0.25, 1)",
      },
      transitionDuration: {
        micro: "120ms",
        fast:  "180ms",
        std:   "320ms",
        slow:  "500ms",
        crate: "600ms",
      },
      maxWidth: {
        content: "1280px",
        prose:   "65ch",
      },
    },
  },
  plugins: [],
}
